### ISSUE TITLE
StackViews preventing touches going through

### ISSUE THREAD

**Issue by HassanSyedt** [syrjs/core#203]
- `syr-cli` version:
- `syr` version:

Relevant code.

```javascript

```

What you did: Had a StackView and a button/touchable opacity inside of it.

What happened: Buttons wouldn't receive their touches.

Reproduction:

-- paste your link here --

Problem description:

Suggested solution: I think for w.e reason the StackView is intercepting touches. It shouldn't do that. The default behavior for something like a stackView should be false for something like allowsTouches

**Comment by dmikey** [comment]
I don't think this is a problem any longer, allowTouches works appropriately ?
