### ISSUE TITLE
StackViews preventing child component rerenders 

### ISSUE THREAD

**Issue by shermango** [syrjs/core#205]
child components are not being rerendered after initial prop pass

**Comment by dmikey** [comment]
![](https://media3.giphy.com/media/11sJtJYfibXrhu/200w.gif?cid=5a38a5a25af0dc746a467871416bb977)

**Comment by shermango** [comment]
IT DOESN'T MATTER WHAT YOUR BUG IS!!!!

**Comment by dmikey** [comment]
All children should re-render appropriately, thanks!
