### ISSUE TITLE
How to run local sample on Android

### ISSUE THREAD

**Issue by brodybits** [syrjs/core#239]
### Problem description:

If I would install and run on Android it starts with a blank screen. Even if I would do `npm install` and `npm run serve` from another window.

I tried running from a2a0dbeeda0b06eed4ed12faec674acb4b1894e3 and changing the IP address to `0.0.0.0:8080`, did not seem to help.

I was able to get a sample to run on iOS (simulator) following the instructions in <https://github.com/syrjs/core#running-the-local-sample>.

### Suggested solution:

Instructions how to run on Android would be much appreciated.

P.S. Getting started directions in <https://syr.js.org/getting_started/> and <https://syr.js.org/cli/> seem to be outdated.

**Comment by dmikey** [comment]
Ah yes, the docs and the CLI are a bit outdated, thanks for checking in on the project, we're feverishly working on updating both of those. For Android local host is mapped to 10.0.2.2 , looks like we have a wonky commit we will get that corrected ASAP.

Thanks!

**Comment by brodybits** [comment]
The following steps do the trick for me:

- go to a2a0dbeeda0b06eed4ed12faec674acb4b1894e3 (currently one back in the `develop` branch)
- do `npm run serve` in its own shell
- `./gradlew installDebug` in the `android` subdirectory to install on an emulator
- run the installed app it on the emulator

b08b82f2b182521ce1f4f7709994318824a2bc66 which is currently the latest commit in `develop` seems to be doing several things at once, wondering if it should be reverted?

**Comment by dmikey** [comment]
Great catch, I'll review that PR more in depth today.

**Comment by brodybits** [comment]
> I'll review that PR more in depth today.

My comments in PR #238. I have contributed the following fixes:
- #241 - fix Android sample asset bundle URL
- #242 - fix the document (quick fix)

**Comment by brodybits** [comment]
Thanks @dmikey for integrating the fixes!

**Comment by dmikey** [comment]
Thanks for contributing!
