### ISSUE TITLE
Where did the name come from?

### ISSUE THREAD

**Issue by brodybits** [syrjs/core#243]
Does "Syr" have a special meaning?

**Comment by dmikey** [comment]
* Three letter anythings are hard to come by
* Syr is closely associated with either a transitive identity or immediate prodigy of Freyja - the goddess of plenty (miss piggy is our mascot)
* The acronym can be construed to include some kind of reference to react `Smaller Younger React` `Stupid easY React` etc (we've not actually coined or settled on anything of the sort though)

Hope that helps!
