### ISSUE TITLE
Working calculator sample

### ISSUE THREAD

**Issue by brodybits** [syrjs/core#258]
The existing calculator.js sample seems to be broken:
- missing operators other than +
- does not seem to really add
- clear button should be added

I can take a look at it sometime in the next month or so.

_P.S. Number buttons are hard to read due to color scheme, especially on iOS._

**Comment by dmikey** [comment]
Thanks this sample is really far from complete, we'll put more time into it.

**Comment by sridharrajs** [comment]
I think we can close this issue @dmikey  since PR #296 addressed this
