### ISSUE TITLE
Stackview Controller is not working as intended

### ISSUE THREAD

**Issue by shermango** [syrjs/core#69]
For some reason stack items are not showing up unless done in pairs, and then every 2nd item "bleeds" on top of the first

<img width="653" alt="screen shot 2018-01-03 at 3 40 48 pm" src="https://user-images.githubusercontent.com/20351341/34544680-9324bf94-f09c-11e7-9b3d-8e80190a7b15.png">

**Comment by dmikey** [comment]
corrected.
